

var grammatikversion=2006;
var grammatik= new Array(



"1.0","abstraktum.html","Abstraktum",
"1.0","adjektiv.html","Adjektiv",
"1.0","adverb.html","Adverb",
"1.0","affix.html","Affix",
"1.0","agens.html","Agens",
"1.0","akkusativ.html","Akkusativ",
"1.0","akkusativobjekt.html","Akkusativobjekt",
"1.0","aktiv.html","Aktiv",
"1.0","akzentuierung.html","Akzentuierung",
"1.0","angleichung.html","Angleichung",
"1.0","antonym.html","Antonym",
"1.0","artikel.html","Artikel",
"1.0","aspekt.html","Aspekt",
"1.0","assimilation.html","Assimilation",
"1.0","attribut.html","Attribut",
"1.0","aufforderungssatz.html","Aufforderungssatz",
"1.0","ausrufesatz.html","Ausrufesatz",
"1.0","aussagesatz.html","Aussagesatz",
"1.0","aussageweise.html","Aussageweise",
"1.0","befehlsform.html","Befehlsform",
"1.0","begriffswort.html","Begriffswort",
"1.0","beiwort.html","Beiwort",
"1.0","besitzanzeigendes_fuerwort.html","Besitzanzeigendes F&uuml;rwort",
"1.0","betonung.html","Betonung",
"1.0","beugung.html","Beugung",
"1.0","dativ.html","Dativ",
"1.0","dativobjekt.html","Dativobjekt",
"1.0","deklarativsatz.html","Deklarativsatz",
"1.0","deklination.html","Deklination",
"1.0","demonstrativpronomen.html","Demonstrativpronomen",
"1.0","diakritisches.html","Diakritisches Zeichen",
"1.0","diminutiv.html","Diminutiv",
"1.0","diphthong.html","Diphthong",
"1.0","direkte.html","Direkte Rede",
"1.0","direktes.html","Direktes Objekt",
"1.0","dual.html","Dual",
"1.0","eigenschaftswort.html","Eigenschaftswort",
"1.0","einzahl.html","Einzahl",
"1.0","entscheidungsfrage.html","Entscheidungsfrage",
"1.0","ergaenzungsfrage.html","Erg&auml;nzungsfrage",
"1.0","exklamativsatz.html","Exklamativsatz",
"1.0","fall.html","Fall",
"1.0","femininum.html","Femininum",
"1.0","finalsatz.html","Finalsatz",
"1.0","flexion.html","Flexion",
"1.0","fragepronomen.html","Fragepronomen",
"1.0","fragesatz.html","Fragesatz",
"1.0","fuerwort.html","F&uuml;rwort",
"1.0","futur1.html","Futur I",
"1.0","futur2.html","Futur II",
"1.0","gegensatzwort.html","Gegensatzwort",
"1.0","gegenstandswort.html","Gegenstandswort",
"1.0","gegenwart.html","Gegenwart",
"1.0","genitiv.html","Genitiv",
"1.0","genus.html","Genus",
"1.0","geschlechtswort.html","Geschlechtswort",
"1.0","gliedsatz.html","Gliedsatz",
"1.0","glossar.html","Glossar",
"1.0","grammatik.html","Grammatik",
"1.0","grundform.html","Grundform",
"1.0","grundstufe.html","Grundstufe",
"1.0","grundzahl.html","Grundzahl",
"1.0","hauptsatz.html","Hauptsatz",
"1.0","hauptwort.html","Hauptwort",
"1.0","hilfsverb.html","Hilfsverb",
"1.0","hinweisendes.html","Hinweisendes F&uuml;rwort",
"1.0","homonymie.html","Homonymie",
"1.0","imperativ.html","Imperativ",
"1.0","imperativsatz.html","Imperativsatz",
"1.0","imperfekt.html","Imperfekt",
"1.0","indefinitpronomen.html","Indefinitpronomen",

"1.0","indikativ.html","Indikativ",
"1.0","indirekte.html","Indirekte Rede",
"1.0","indirektes.html","Indirektes Objekt",
"1.0","infinitiv.html","Infinitiv",
"1.0","infix.html","Infix",

"1.0","instrumental.html","Instrumental",
"1.0","interrogativpro.html","Interrogativpronomen",
"1.0","interrogativs.html","Interrogativsatz",
"1.0","intransitives.html","Intransitives Verb",
"1.0","irrealis.html","Irrealis",
"1.0","kardinalzahl.html","Kardinalzahl",
"1.0","kasus.html","Kasus",
"1.0","kausalsatz.html","Kausalsatz",
"1.0","komparation.html","Komparation",
"1.0","komparativ.html","Komparativ",
"1.0","konjugation.html","Konjugation",
"1.0","konjunktion.html","Konjunktion",
"1.0","konjunktiv.html","Konjunktiv",
"1.0","konjunktiv1.html","Konjunktiv I",
"1.0","konjunktiv2.html","Konjunktiv II",
"1.0","konkretum.html","Konkretum",
"1.0","konsonant.html","Konsonant",
"1.0","kontext.html","Kontext",
"1.0","kopulaverb.html","Kopulaverb",
"1.0","korrelat.html","Korrelat",
"1.0","laut.html","Laut",
"1.0","leideform.html","Leideform",
"1.0","linguistik.html","Linguistik",
"1.0","lokativ.html","Lokativ",
"1.0","maennlich.html","M&auml;nnliches Geschlecht",
"1.0","maskulinum.html","Maskulinum",
"1.0","mehrstufe.html","Mehrstufe",
"1.0","mehrzahl.html","Mehrzahl",
"1.0","meiststufe.html","Meiststufe",
"1.0","mitlaut.html","Mitlaut",
"1.0","mittelwort.html","Mittelwort",
"1.0","modalsatz.html","Modalsatz",
"1.0","modalverb.html","Modalverb",
"1.0","modus.html","

Modus",
"1.0","moeglichkeit_2.html","M&ouml;glichkeitsform: Konjunktiv",
"1.0","moeglichkeit.html","M&ouml;glichkeit",
"1.0","monophthong.html","Monophthong",
"1.0","nebensatz.html","Nebensatz",
"1.0","negation.html","Negation",
"1.0","neutrum.html","Neutrum",
"1.0","nomen.html","Nomen",
"1.0","nominativ.html","Nominativ",
"1.0","numerale.html","Numerale",
"1.0","numerus.html","Numerus",
"1.0","objekt.html","Objekt",
"1.0","ordinalzahl.html","Ordinalzahl",
"1.0","ordnungszahl.html","Ordnungszahl",
"1.0","orthographie.html","Orthographie",
"1.0","partikel.html","Partikel",
"1.0","partizip_1.html","Partizip I",
"1.0","partizip_2.html","Partizip II",
"1.0","partizip.html","Partizip",
"1.0","passiv.html","Passiv",
"1.0","patiens.html","Patiens",
"1.0","perfekt.html","Perfekt",
"1.0","personalpronomen.html","Personalpronomen",
"1.0","person.html","Person",
"1.0","phonetik.html","Phonetik",
"1.0","pluraletantum.html","Pluraletantum",
"1.0","plural.html","Plural",
"1.0","plusquamperfekt.html","Plusquamperfekt",
"1.0","polysemie.html","Polysemie",
"1.0","positiv.html","Positiv",
"1.0","possessivpronomen.html","Possessivpronomen",
"1.0","postposition.html","Postposition",
"1.0","praedikat.html","Pr&auml;dikat",
"1.0","praedikativ.html","Pr&auml;dikativ",
"1.0","praedikatsnomen.html","Pr&auml;dikatsnomen",
"1.0","praefix.html","Pr&auml;fix",
"1.0","praeposition.html","Pr&auml;position",
"1.0","praesens.html","Pr&auml;sens",
"1.0","praeteritum.html","Pr&auml;teritum",
"1.0","pragmatik.html","Pragmatik",
"1.0","pronomen.html","Pronomen",
"1.0","rechtschreibung.html","Rechtschreibung",
"1.0","relativpronomen.html","Relativpronomen",
"1.0","relativsatz.html","Relativsatz",
"1.0","rhetorik.html","Rhetorik",
"1.0","rhetorische.html","Rhetorische Frage",
"1.0","saechliches.html","S&auml;chliches Geschlecht",
"1.0","satzaussage.html","Satzaussage",
"1.0","satzglied.html","Satzglied",
"1.0","satz.html","Satz",
"1.0","semantik.html","Semantik",
"1.0","singularetantum.html","Singularetantum",
"1.0","singular.html","Singular",
"1.0","sprachwissenschaft.html","Sprachwissenschaft",
"1.0","steigerung_1.html","Steigerung I",
"1.0","steigerung.html","Steigerung II",
"1.0","subjekt.html","Subjekt",
"1.0","substantiv.html","Substantiv",
"1.0","substantivierung.html","Substantivierung",
"1.0","suffix.html","Suffix",
"1.0","superlativ.html","Superlativ",
"1.0","synonym.html","Synonym",
"1.0","syntax.html","Syntax",
"1.0","taeter.html","T&auml;ter",
"1.0","taetigkeitswort.html","T&auml;tigkeitswort",
"1.0","tempus.html","Tempus",
"1.0","transitives.html","Transitives Verb",
"1.0","umstandswort.html","Umstandswort",
"1.0","unbestimmmtes.html","Unbestimmtes F&uuml;rwort",
"1.0","verb.html","Verb",
"1.0","verkleinerungsform.html","Verkleinerungsform",
"1.0","verneinung.html","Verneinung",
"1.0","vokal.html","Vokal",
"1.0","vollendete.html","Vollendete Gegenwart",
"1.0","vollverb.html","Vollverb",
"1.0","vorvergangenheit.html","Vorvergangenheit",
"1.0","weibliches.html","Weibliches Geschlecht",
"1.0","wemfall.html","Wemfall",
"1.0","wenfall.html","Wenfall",
"1.0","werfall.html","Werfall",
"1.0","wesfall.html","Wesfall",
"1.0","wiewort.html","Wiewort",
"1.0","wirklichkeitsform.html","Wirklichkeitsform",
"1.0","wortart.html","Wortart",
"1.0","wortfamilie.html","Wortfamilie",
"1.0","wort.html","Wort",
"1.0","wortschatz.html","Wortschatz",
"1.0","wunschsatz.html","Wunschsatz",
"1.0","zahladjektiv.html","Zahladjektiv",
"1.0","zahl.html","Zahl",
"1.0","zeit.html","Zeit",
"1.0","zeitwort.html","Zeitwort",
"1.0","zirkumposition.html","Zirkumposition",
"1.0","zukunft_1.html","Zukunft: Futur I",
"1.0","zukunft_2.html","Zukunft: Futur II",
"1.0","zusammenhang.html","Zusammenhang",


);






function grammar(nummer,grammatik2)
{
  var c=0;
  while(grammatik[c])
  {
    if (grammatik[c] == nummer){

      if (grammatik2==1){
        document.write("<tr align=center><td bgcolor=#FFFFFF onMouseout=\"this.style.backgroundColor='#FFFFFF'\" onMouseover=\"this.style.backgroundColor='#F6E9A0'\"><font size=2 face='verdana,arial,helvetica' color=000000><a href=\"../grammatik/"+grammatik[c+1]+"\" target=rahmen1>"+grammatik[c+2]+"</u></td></tr>");
      }
      else
      {
        document.write("<tr align=center><td bgcolor=#FFFFFF onMouseout=\"this.style.backgroundColor='#FFFFFF'\" onMouseover=\"this.style.backgroundColor='#F6E9A0'\"><table border=0 cellpadding=0 cellspacing=0><tr align=center><td><font size=2>\&nbsp;\&nbsp;</td><td><font size=2 face='verdana,arial,helvetica' color=000000><a href=\"../grammatik/"+grammatik[c+1]+"\" target=rahmen1>"+grammatik[c+2]+"</u></td></tr></table></td></tr>");
      }
    }
    c=c+3;
  }
}









